baseurl = "http://jillandnick.wedding"
languageCode = "en-us"
title = "Jill & Nick Are Getting Married!"
theme = "Agency"
googleAnalytics = "UA-77207901-1"

[params]
  # search engine meta
	name = "Nick Spreitzer"
	description = "Nick Spreitzer and Jill Ott Wedding Website October 15th 2016"
  email = "us@jillandnick.wedding"

# Navigation
[params.navigation]
  brand = "Jill & Nick's Wedding"
  weddingDetails = "Wedding Details"
	hotelBlock = "Hotel Block"
  registry_list = "Gift Registries"
	team = "About Us"
	# contact = "Contact"

[[menu.postpend]]
  url = "http://jillandnickwedding.app.rsvpify.com/"
  name = "RSVP!"
  weight = 10

[params.hero]
	title = "Jill & Nick Are Getting Married!"
	subtitle = "October 15, 2016"
	buttonText = "Read More"

[params.weddingDetails]
  enable = true
  title = "Wedding Details"
  subtitle = "The 'Where' and 'When'. We already know 'Who'!"

  [[params.weddingDetails.row]]

    [[params.weddingDetails.row.list]]
        icon = "fa-heart"
        title = "The Ceremony"
        description = "The ceremony will be held at (approximately) 6:00 PM, at the gazebo at [Star Hill Ranch](http://www.starhillranch.com) on Saturday October 15, 2016. The exact time is subject to change as we get closer to the actual date. We're aiming for a sunset ceremony."

    [[params.weddingDetails.row.list]]
        icon = "fa-glass"
        title = "The Reception"
        description = "A cocktail hour and then the reception will be held at the [old school house](http://www.starhillranch.com/images/gallery/015.jpg) at Star Hill Ranch, immediately following the ceremony. And after that... we expect to join up at the gorgeous rooftop bar of the Sonesta hotel for continued libations!"

    [[params.weddingDetails.row.list]]
        icon = "fa-black-tie"
        title = "The Style"
        description = "We're going for a semi-formal/rustic-chic motif. So, what should you wear? Just try to dress pretty and you'll probably be fine. Cowboy boots and hats are welcome. (After all, this *is* Texas, y'all!) Guys, ties are *not* required. For the ladies, the bride requests you just refrain from wearing a wedding dress. ;-)"

  [[params.weddingDetails.row]]

    [[params.weddingDetails.row.list]]
        icon = "fa-building"
        title = "The Venue"
        description = "[Star Hill Ranch](http://www.starhillranch.com/) is reminiscent of a quaint little Hill Country town from the early 1900s. All of the 22 historic buildings, originally constructed between 1850 and 1935, have been relocated from around the state and carefully restored. We can't wait to share this unique and memorable place with you!"

    [[params.weddingDetails.row.list]]
        icon = "fa-bed"
        title = "Hotels"
        description = "We have a [hotel room block at Sonesta Bee Cave](#hotel-block), and we strongly encourage everyone to take advantage of the great deal we are getting at this fantastic new hotel. However, if you prefer an alternative, there are two other hotels nearby: [Mountain Star Hotel](http://www.mountainstarlodge.com/) and [Hampton Inn & Suites](http://hamptoninn3.hilton.com/en/hotels/texas/hampton-inn-and-suites-austin-lakeway-AUSLWHX/index.html). Keep in mind, the Sonesta provides a shuttle to Star Hill Ranch; other hotels may not provide this service."

    [[params.weddingDetails.row.list]]
        icon = "fa-plane"
        title = "Flight Info"
        description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit."

  [[params.weddingDetails.row]]

    [[params.weddingDetails.row.list]]
        icon = "fa-car"
        title = "Car Rentals"
        description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit."

[params.hotelBlock]
  enable = true
	title = "Hotel Block"
	subtitle = "Lorem ipsum dolor sit amet consectetur."

[params.registry_list]
  enable = true
  title = "Gift Registries"
  subtitle = "Lorem ipsum dolor sit amet consectetur."
  description = "We're registered with one traditional retailer, **Bed Bath & Beyond**. Please click the **blue logo** above to view our selection of Bed Bath & Beyond items. Alternatively, if you'd like to contribute to our **honeymoon fund**, please click the **red suitcase icon** above to send us any amount you choose. We're planning on going somewhere in the South Pacific! (Think: Bora Bora) Check back later for more updates on our plans."

  [[params.registries]]
    logo = "bed-bath-logo.png"
    link = "http://www.bedbathandbeyond.com/store/giftregistry/view_registry_guest.jsp?pwsToken=&eventType=Wedding&registryId=542989226&wcref=yes&wcsid=293540525"

  [[params.registries]]
    logo = "honeymoon-fund.png"
    link = "https://www.paypal.me/jillandnickhoneymoon"

[params.team]
  enable = true
	title = "The Couple"
	subtitle = "Couples that ski together, stay together. Or something like that. :)"
	description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut eaque, laboriosam veritatis, quos non quis ad perspiciatis, totam corporis ea, alias ut unde."

	[[params.team.members]]
		img = "jill-solo.jpg"
		name = "Jill Ott"
		position = "Future Wife"
		social = [
			["fa-facebook", "https://www.facebook.com/jillannott"]
		]

	[[params.team.members]]
		img = "me-solo.jpg"
		name = "Nick Spreitzer"
		position = "Future Husband"
		social = [
			["fa-facebook", "https://www.facebook.com/nspreitzer"]
		]

  [params.about]
    title = "Our Story"
    subtitle = "Lorem ipsum dolor sit amet consectetur."
    endpoint = "Be part<br>of our<br>story!"

    	[[params.about.events]]
    		img = "1.jpg"
    		date = "2009-2011"
    		title = "Our Humble Beginnings"
    		description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"

    	[[params.about.events]]
    		img = "2.jpg"
    		date = "March 2011"
    		title = "An Agency is Born"
    		description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"

    	[[params.about.events]]
    		img = "3.jpg"
    		date = "December 2012"
    		title = "Our Humble Beginnings"
    		description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"

    	[[params.about.events]]
    		img = "4.jpg"
    		date = "July 2014"
    		title = "Phase Two Expansion"
    		description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"

# Contact section
[params.contact]
  enable = true
	title = "Contact us"
	subtitle  = "Lorem ipsum dolor sit amet consectetur."
	buttonText = "Send message"

	# 'warning' defines error messages for invalid inputs
	[params.contact.form.name]
		text = "Your Name *"
		warning = "Please enter your name."

	[params.contact.form.email]
		text = "Your Email *"
		warning = "Please enter your email address."

	[params.contact.form.phone]
		text = "Your Phone *"
		warning = "Please enter your phone number."

	[params.contact.form.message]
		text = "Your Message *"
		warning = "Please enter a message."

[params.footer]
  enable = true
	copyright = "**You an oak man?** *Oak's nice.*"

[[params.footer.quicklinks]]
	text = "Theme forked from Hugo Agency"
	link = "https://github.com/digitalcraftsman/hugo-agency-theme"
